services:
  web:
    build: .
    ports:
      -5000:5000
      -9229:9229 #this exanbles debugging later.
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn dev
    environment:
      - PORT=5000